version: "3.8"

services:
  backend:
    container_name: "rest_api"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - fullstack
  postgres:
    container_name: "database"
    image: postgres:13-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo_challenge
    ports:
      - "5432:5432"
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge