apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend-app
      tier: backend
  template:
    metadata:
      labels:
        app: todo-backend-app
        tier: backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: todo-backend
          image: mustafatoker/todo-backend:latest
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: "250m"
              memory: "64M"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: todo-backend-app
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: todo-backend-app
    tier: backend