name: Backend Pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test -v ./tests
      - name: Fetch required Go modules
        run: go mod download
      - name: Build
        run: go build -o todo-app ./main.go
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest