name: Backend Pipeline
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: todo-cluster
  GKE_ZONE: europe-central2-a
  DEPLOYMENT_NAME: gke-prod
  IMAGE: mustafatoker/todo-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test -v ./tests
      - name: Fetch required Go modules
        run: go mod download
      - name: Build
        run: go build -o todo-app ./main.go
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mustafatoker/todo-backend:latest, mustafatoker/todo-backend:1.0.5
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: |-
          gcloud --quiet auth configure-docker
      - uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      - name: apply && wait
        run: kubectl apply -f kubernetes/postgresql-deployment.yml && kubectl wait --for=condition=ready pod -l app=postgresql-db --timeout=600s
      - name: apply && wait
        run: kubectl apply -f kubernetes/backend-deployment.yml && kubectl wait --for=condition=ready pod -l app=todo-backend-app --timeout=600s
